_wandb:
    value:
        cli_version: 0.19.5
        code_path: code/PA1.py
        m: []
        python_version: 3.8.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.8.3
            "5": 0.19.5
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
env_name:
    value: ALE/SpaceInvaders-v5
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 10000
