_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[[ 0  0  0 ...  0  0  0]
           [ 0  0  0 ...  0  0  0]
           [ 0  0  0 ...  0  0  0]
           ...
           [80 80 80 ... 80 80 80]
           [80 80 80 ... 80 80 80]
           [80 80 80 ... 80 80 80]]

          [[ 0  0  0 ...  0  0  0]
           [ 0  0  0 ...  0  0  0]
           [ 0  0  0 ...  0  0  0]
           ...
           [89 89 89 ... 89 89 89]
           [89 89 89 ... 89 89 89]
           [89 89 89 ... 89 89 89]]

          [[ 0  0  0 ...  0  0  0]
           [ 0  0  0 ...  0  0  0]
           [ 0  0  0 ...  0  0  0]
           ...
           [22 22 22 ... 22 22 22]
           [22 22 22 ... 22 22 22]
           [22 22 22 ... 22 22 22]]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001674C78FDC0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 10000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.5
        code_path: code/PA1.py
        m: []
        python_version: 3.8.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.8.3
            "5": 0.19.5
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Discrete(6)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000001674C7CD430>
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x000001674C763520>
env_name:
    value: ALE/SpaceInvaders-v5
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000001674C7A9040>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(0, 255, (3, 210, 160), uint8)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=100800, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=100800, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
policy_type:
    value: MlpPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001674C763670>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1738262183009557400
target_kl:
    value: None
tensorboard_log:
    value: runs/9ldubolx
total_timesteps:
    value: 10000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
